---
title: "sixseven_recording_ages"
author: "sd"
date: "9/15/2017"
output: html_document
---

```{r setup, echo=FALSE, results='hide', message=FALSE}
#setwd("/Users/sd314/Desktop/github/blab/talk_youre_on_camera")
library(dplyr)

require("knitr")
knitr::opts_chunk$set(cache=TRUE, fig.width = 20, fig.height=10, warning = F, strip.white = T)
#opts_knit$set(root.dir = "/Users/sd314/Desktop/github/blab/talk_youre_on_camera")
```

``` {r reading in the data, echo=FALSE, results='hide', message=FALSE}
visit_ages <- read.csv("data/sixseven_visit_ages.csv")
```

``` {r prep, echo=FALSE, results='hide', message=FALSE}
visit_ages_6 <- visit_ages %>%
  filter(month == "6")

visit_ages_7 <- visit_ages %>%
  filter(month == "7")
```

``` {r function, echo=FALSE}

# MM;DD function

mmdd <- function(mean,sd) {
  mos <- floor(mean/30.42)
  days <- round(mean-(mos*30.42),digits = 0)
    step2 <- c("M=",mos,";",days,", SD=",round(sd,digits = 1)," days")
    result <- paste(step2, sep="", collapse="") 
    return(result)
}
```

``` {r 6mo, echo=FALSE}
# 6mo lab visit
sixmo_lab = mmdd(mean(visit_ages_6$lab_age_days),sd(visit_ages_6$lab_age_days))

# 6mo audio
sixmo_audio = mmdd(mean(visit_ages_6$audio_age_days),sd(visit_ages_6$audio_age_days))

# 6mo video
sixmo_video = mmdd(mean(visit_ages_6$video_age_days),sd(visit_ages_6$video_age_days))
```

``` {r 7mo, echo=FALSE}

# 7mo audio
sevenmo_audio = mmdd(mean(visit_ages_7$audio_age_days),sd(visit_ages_7$audio_age_days))

# 7mo video
sevenmo_video = mmdd(mean(visit_ages_7$video_age_days),sd(visit_ages_7$video_age_days))
```

``` {r table prep, echo=FALSE}
Month = c("6 months","7 months")
  
Video_recordings = c(sixmo_video,sevenmo_video)

Audio_recordings = c(sixmo_audio,sevenmo_audio)

Lab_visits = c(sixmo_lab,"NA")

col_names = c("","Video recordings","Audio recordings","In-lab visits")
  
table_data <- data.frame(Month, Video_recordings, Audio_recordings, Lab_visits)
```


``` {r kable, echo=FALSE}
kable(table_data, col.names = col_names, format = "markdown", padding = 2)
```


